version = 0.1

[default.deploy]
[default.deploy.parameters]
template_file = "template.yaml"
stack_name = "profile-site"
region = "ap-northeast-1"
s3_prefix = "profile-site"
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
parameter_overrides = [
    "DomainName=gomorishita.com",
    "HostedZoneId=Z049227635F0NK62EPFCW",
    "CertificateArn='arn:aws:acm:ap-northeast-1:890742577378:certificate/564b381d-0527-4bc3-8e28-e761e6055e15'"
]
fail_on_empty_changeset = false
resolve_s3 = true
