version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd frontend
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync out/ s3://${ClientBucketName}/ --delete
      - aws cloudfront create-invalidation --distribution-id ${ClientDistributionId} --paths "/*"